FROM kehuo/centos8_conda:v1

WORKDIR /data/project

# ADD ./package.json ./
# RUN npm -g install gulp@3.9.1  && npm install
# COPY ./resource/nginx.conf /etc/nginx/
# COPY ./resource/default.conf /etc/nginx/conf.d/
