from kehuo/debian_nginx:conda_git_vim as builder

ENV PYTHONIOENCODING utf-8
ENV LANG en_US.UTF-8


WORKDIR /data/project

ADD ./resource/default.conf ./default.conf
ADD ./resource/pip.conf /root/.pip/
ADD ./requirements.txt ./requirements.txt
ADD ./service.conf ./service.conf

RUN source ~/.bashrc \
    && conda activate myenv \
    && pip install --upgrade pip && pip install Cython && pip install path.py \
	&& pip install -r ./requirements.txt

ADD ./ ./

# RUN source ~/.bashrc \
#    && conda activate myenv \
#    && pip install --upgrade pip && pip install Cython && pip install path.py \
# 	 && pip install -r ./requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

